# Generated by Django 2.0.5 on 2018-05-04 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_homeinv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='groups')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='groups',
            field=models.ManyToManyField(to='app_homeinv.Group'),
        ),
    ]
